### ISSUE TITLE
When Setting up two kafka clusters in the same namespace cruisecontrol restarts constantly 

### ISSUE THREAD

**Issue by matt-christiansen-exa** [banzaicloud/kafka-operator#101]
**Describe the bug**

I was testing out this Kafka Operator, and one of my use cases is I need to spawn more than one cluster per namespace. If I enable CruiseControl for two clusters in the same namespace the crusisecontrol config constantly gets overwritten by the operator and the two cluster configs. 

The only I can stop it is to delete the second cluster. I have tried editing a number of configs and it doesn't seem to matter. Based on the documentation for CruiseControl it would seem we need to deploy a cruisecontrol instance per broker cluster. 

**Steps to reproduce the issue:**

I can share my manifests if you want (they are long) but basically apply the one in https://github.com/banzaicloud/kafka-operator/blob/master/config/samples/banzaicloud_v1alpha1_kafkacluster.yaml and the second time change the name field to anything other than `kafka` 

**Expected behavior**
That it deploys the second cluster and cruisecontrol can balance/maintain it. 

**Screenshots**

**Additional context**
```
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: kafka-operator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: kafka-operator
    app.kubernetes.io/version: 0.5.2
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
    helm.sh/chart: kafka-operator-0.0.11
```

**Comment by baluchicken** [comment]
Hi, @matt-christiansen-exa thanks for the detailed issue. We are going to investigate this and get back to you with our findings.

**Comment by baluchicken** [comment]
@matt-christiansen-exa we just released a [new version](https://github.com/banzaicloud/kafka-operator/releases/tag/0.5.3) from the operator which fixes your problem, thanks for reporting it.
