### ISSUE TITLE
Can we support nodeport for external listener access instead of lb?

### ISSUE THREAD

**Issue by yeya24** [banzaicloud/kafka-operator#107]
**Is your feature request related to a problem? Please describe.**

I want to deploy this operator in my private k8s with the default yaml kafkacluster_without_ssl.yml. But it failed because operator wanted to get the ip of lb. Can I deploy this without lb? I just want to use NodePort.

**Describe the solution you'd like to see**
A clear and concise description of what would you like to happen.

**Describe alternatives you've considered**

**Additional context**

**Comment by baluchicken** [comment]
Hi @yeya24,

Thanks for opening this issue.
Yes you can deploy the cluster without LB. Please remove the `externalListeners` [block](https://github.com/banzaicloud/kafka-operator/blob/master/config/samples/kafkacluster_without_ssl.yaml#L54) from the CR. 

Supporting NodePort as external access is indeed a good idea.
We are planning to support this mode.

In the meantime, if you are interested consider submitting a PR.
I am happy to help with the process.

**Comment by yeya24** [comment]
Yes, I' d like to work at this. But I need to get familiar this code first :smile:

**Comment by baluchicken** [comment]
Cool, please let me know if you need help

**Comment by baluchicken** [comment]
Hi @yeya24 

First we should introduce a new field to the CRD something called `ServiceType` where the user can specify if the external service is NodePort or LoadBalancer based.
LoadBalancer deploys Envoy as a proxy, which is not required in case of NodePort access.
We should create as many "nodeport" service as Kafka brokers. 
NodePorts are available on all nodes but since Kafka brokers can advertise one address/listener, we should advertise the node where the pod/broker is scheduled.

The external listener now looks like this, we think we should use the `ExternalStartingPort+brokerID` to specify the NodePorts for the brokers.
```
// ExternalListenerConfig defines the external listener config for Kafka
type ExternalListenerConfig struct {
	Type                 string `json:"type"`
	Name                 string `json:"name"`
	ExternalStartingPort int32  `json:"externalStartingPort"`
	ContainerPort        int32  `json:"containerPort"`
}
```

I hope these infos gives you enough information, but if I missed something don't hesitate to contact us. Either here or on our [community-slack](https://slack.banzaicloud.io/)
Thanks

**Comment by yeya24** [comment]
> Hi @yeya24
> 
> First we should introduce a new field to the CRD something called `ServiceType` where the user can specify if the external service is NodePort or LoadBalancer based.
> LoadBalancer deploys Envoy as a proxy, which is not required in case of NodePort access.
> We should create as many "nodeport" service as Kafka brokers.
> NodePorts are available on all nodes but since Kafka brokers can advertise one address/listener, we should advertise the node where the pod/broker is scheduled.
> 
> The external listener now looks like this, we think we should use the `ExternalStartingPort+brokerID` to specify the NodePorts for the brokers.
> 
> ```
> // ExternalListenerConfig defines the external listener config for Kafka
> type ExternalListenerConfig struct {
> 	Type                 string `json:"type"`
> 	Name                 string `json:"name"`
> 	ExternalStartingPort int32  `json:"externalStartingPort"`
> 	ContainerPort        int32  `json:"containerPort"`
> }
> ```
> 
> I hope these infos gives you enough information, but if I missed something don't hesitate to contact us. Either here or on our [community-slack](https://slack.banzaicloud.io/)
> Thanks

Thank you for your help. I think the logic in the package `envoy`. And I just need to deal with the NodePort logic when `servicetype` field equals `nodePort`. Is it better to change package name of `envoy` to something else?

**Comment by baluchicken** [comment]
I think maybe  we should create a package externalAccess and move the envoy package and the newly created nodePort related package inside that. I would keep the envoy package and create a different one which contains only the NodePort related implementation.

**Comment by yeya24** [comment]
Do you still need externalStartingPort for NodePort ServiceType? Because NodePort has a valid range which is from 30000 to 32768. Also some ports in this range maybe allocated by other processes. So what about don't specify NodePort and let it generated automatically by k8s? When generating kafka configs, we can get it by k8s client because we also need to get the node address.

**Comment by baluchicken** [comment]
@yeya24 Okey, I like the idea where the K8s automatically generates the Nodeport, let's set omitempty to `externalStartingPort` so it can be left empty.

**Comment by baluchicken** [comment]
After release 0.14.0 we are supporting nodeport external access type.
