### ISSUE TITLE
Bump Kafka-Operator helm chart to use Prometheus Operator

### ISSUE THREAD

**Issue by baluchicken** [banzaicloud/kafka-operator#125]
**Describe the bug*
In this PR we changed the label names used to get cr in case of an alert from `kubernetes_namespace` -> `namespace`
https://github.com/banzaicloud/kafka-operator/pull/96

This new labelling requires a Prometheus which was installed by the Prometheus Operator.
Replace the operator helm chart requirement to use the Prometheus Operator chart instead.

**Comment by pbalogh-sa** [comment]
fixed in: #129
