### ISSUE TITLE
brokerConfig.config is not copied to configmap

### ISSUE THREAD

**Issue by prune998** [banzaicloud/kafka-operator#154]
Considering a `kafkacluster` defined like : 
 - kafka operator 0.6.0
- cluster name `kf-kafka`
- brokers section in the `kafkacluster` yaml : 
```
  brokers:
    - id:  0
      brokerConfigGroup: "default_group"
      brokerConfig:
        resourceRequirements:
          limits:
            memory: "3Gi"
          requests:
            cpu: "0.3"
            memory: "512Mi"
        config: |
          session.timeout.ms=20000
          offsets.topic.replication.factor=2
          ProducerConfig.RETRIES_CONFIG=10
          transaction.state.log.replication.factor=2
          transaction.state.log.min.isr=1
          log.dirs=/kafka-logs/data
          ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG=1000
          delete.topic.enable=true
          num.partitions=32
          auto.create.topics.enable=false
          default.replication.factor=2
          num.recovery.threads.per.data.dir=8
```

The configmap `kf-kafka-config-0` created is like : 
```
apiVersion: v1
data:
  broker-config: |-
    advertised.listeners=PLAINTEXT://kf-kafka-0.alerting.svc.cluster.local:9092
    broker.id=0
    broker.rack=francecentral,3
    cruise.control.metrics.reporter.bootstrap.servers=PLAINTEXT://kf-kafka-0.alerting.svc.cluster.local:9092
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT
    listeners=PLAINTEXT://:9092
    log.dirs=/kafka-logs/kafka
    metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter
    security.inter.broker.protocol=PLAINTEXT
    super.users=
    zookeeper.connect=zk-zookeeper.alerting:2181
kind: ConfigMap
metadata:
  annotations:
  labels:
    app: kafka
    brokerId: "0"
    kafka_cr: kf-kafka
  name: kf-kafka-config-0
  namespace: alerting
  ownerReferences:
  - apiVersion: kafka.banzaicloud.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: KafkaCluster
    name: kf-kafka
```

Is it normal that the special config parameters are not set there ?

**Comment by baluchicken** [comment]
Yes it is totally normal, since that configuration is a dynamic configuration which is stored in Zookeeper, the operator will only save the read only configs to ConfigMap and store all others in Zookeeper. https://kafka.apache.org/documentation/#dynamicbrokerconfigs

**Comment by baluchicken** [comment]
I just noticed that not all your configs are fine, with this new version of the operator you must distinguish your configs like Kafka does, `read-only`, `per-broker`, `cluster-wide`. The read only configs should go to the read-only section of the crd and so on.

**Comment by prune998** [comment]
OK I'll arrange that. Thanks for the info. I'm used to have all the config in one place, but I guess you need this so the Operator knows if it have to apply them dynamically or do a restart....

**Comment by prune998** [comment]
After splitting all the config in the right place everything is working fine.
Thanks.
