### ISSUE TITLE
RFC : Operator behaviour when a Topic is manually deleted from Kafka ? 

### ISSUE THREAD

**Issue by prune998** [banzaicloud/kafka-operator#158]
With Kafka Operator 0.6.x there is support for Topic Management.
When we create a `kafkatopic` CR, the corresponding topic is created in Kafka. 

When you delete the topic from Kafka by hand, the operator loops through an error : 
```
kafka-operator-7bc9c8cd8f-l4qxk manager 2019-10-01T15:26:51.139Z	INFO	controllers.KafkaTopic.alerting/example-topic_sync	Syncing topic status
kafka-operator-7bc9c8cd8f-l4qxk manager 2019-10-01T15:26:51.233Z	ERROR	controllers.KafkaTopic.alerting/example-topic_sync	Failed to describe topic to update its status	{"error": "kafka server: Request was for a topic or partition that does not exist on this broker."}
kafka-operator-7bc9c8cd8f-l4qxk manager github.com/go-logr/zapr.(*zapLogger).Error
kafka-operator-7bc9c8cd8f-l4qxk manager 	/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
kafka-operator-7bc9c8cd8f-l4qxk manager github.com/banzaicloud/kafka-operator/controllers.(*KafkaTopicReconciler).doTopicStatusSync
kafka-operator-7bc9c8cd8f-l4qxk manager 	/workspace/controllers/kafkatopic_controller.go:269
kafka-operator-7bc9c8cd8f-l4qxk manager github.com/banzaicloud/kafka-operator/controllers.(*KafkaTopicReconciler).syncTopicStatus
kafka-operator-7bc9c8cd8f-l4qxk manager 	/workspace/controllers/kafkatopic_controller.go:234
```

The `kafkatopic` CR is not enforced and the topic is not re-created.

**Should the Kafka Operator enforce presence of topics in `kafkatopic` and re-create it ?**

Note that even once the topic does not exist in Kafka, deleting the `kafkatopic` CR is well handled by the Operator : 
```
Topic has been deleted, stopping sync routine
```

**Comment by tinyzimmer** [comment]
Just to add to the discussion - what should be the desired behavior when a cluster has topic deletion disabled and a `KafkaCluster` or `KafkaTopic` gets deleted? In the current state on `master`, if I am understanding `sarama`'s documentation correctly, is that no error will be raised but the topic will remain in Kafka/Zookeeper. So an attempt to recreate the topic on a new or existing cluster using the same zookeeper will fail.

**Comment by baluchicken** [comment]
From Kubernetes perspective Kafka Topics and Users are external resources. In release 0.7.0 we removed the loop which periodically checked Kafka Topics. Since it is an external resource the operator will not receive any event in case of modification. I think this is the way to go. 
It has some benefits like we don't need to implement an inner watcher logic for the Kafka resources.
Of course it has some drawbacks as well since if the user deletes a topic created through CR the operator will recreate it once an update happens on the related CR.

**Comment by prune998** [comment]
That's a fair move. Now we know how to handle such a situation. Thanks @baluchicken 
Is this clearly stated in the docs ? (will check ASAP)
I think this can be closed then.

Thanks again for your great work
