### ISSUE TITLE
How to communicate with the Kafka Service?

### ISSUE THREAD

**Issue by JohnAntonusMaximus** [banzaicloud/kafka-operator#181]
If we're using Kafkacat, how do we create/list a topic with the below pods and services in namespace 'kafka'? is it the cruise-control service that is the client/ingress?

Pods

Thanks!

**Comment by baluchicken** [comment]
Hi, you have two options:

- Using the headless service the `kafka-headless:29092`
- Or communicating with the kafka brokers directly via `kafka-<brokerid>.kafka-headless.kafka.svc.cluster.local:29092`

**Comment by baluchicken** [comment]
We hope we answered your question, so closing this. Please contact us here or on our community [slack](https://slack.banzaicloud.io/) if you need more help.
