### ISSUE TITLE
Install cruise control

### ISSUE THREAD

**Issue by palmerabollo** [banzaicloud/kafka-operator#185]
There is one thing that is not clear to me: the README details how to install all the third-party components that kafka-operator needs to run: cert-manager, prometheus, zookeeper... But it doesn't say anything about cruise control.

Is it because it is deployed as part of a KafkaCluster? Any recommendations or recommended manifests/charts to deploy a cruise control instance that works well with the simplekafkacluster.yml example?

Thank you.

**Comment by baluchicken** [comment]
Hi, thanks for the issue. The operator automatically installs the Cruise Control for the Kafka Cluster. You don't need to install it separately. On the other hand if you have an already running Cruise Control you can specify it on the CR and the operator will try to connect and use that.

**Comment by baluchicken** [comment]
We hope we answered your question, so closing this. Please contact us here or on our community [slack](https://slack.banzaicloud.io/) if you need more help.
