### ISSUE TITLE
nodeSelector indentation should be fixed

### ISSUE THREAD

**Issue by fireking77** [banzaicloud/kafka-operator#216]
**Describe the bug**
The nodeSelector indentation here needs to be fixed: 
https://github.com/banzaicloud/kafka-operator/blob/master/charts/kafka-operator/templates/operator-deployment.yaml#L106

fix: please remove 1 tab, or use absolute indentation

**Steps to reproduce the issue:**
I was not able to use nodeSelector without manually fixing it

**Expected behavior**
I would like to use your chart without fixing it manually

**Comment by baluchicken** [comment]
Thanks for reporting it we are going to fix this ASAP

**Comment by baluchicken** [comment]
@fireking77 we just fixed this. The new version of the chart 0.2.9 should work as intended.
