### ISSUE TITLE
Installation docs update

### ISSUE THREAD

**Issue by OuesFa** [banzaicloud/kafka-operator#220]
Hello 

Seems that installation docs are not up to date with helm 3 specifications.

While installing cert-manager it's not possible anymore to specify name option anymore.
So basically it's
`helm install cert-manager --namespace cert-manager --version v0.11.0 jetstack/cert-manager`
rather than 
`helm install --name cert-manager --namespace cert-manager --version v0.11.0 jetstack/cert-manager
`
I'm new to Kubernetes ecosystem so sorry if it's not relevant issue.

Thanks

**Comment by pbalogh-sa** [comment]
@OuesFa  Thanks for reporting this.

**Comment by OuesFa** [comment]
Thanks for your answer.
I opened a PR, my first one :)
