### ISSUE TITLE
make deploy cannot deploy the kafka operator

### ISSUE THREAD

**Issue by seecsea** [banzaicloud/kafka-operator#222]
**Describe the bug**
make deploy cannot deploy the kafka operator:

**Steps to reproduce the issue:**
# make deploy 
/root/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/base/crds output:rbac:artifacts:config=config/base/rbac output:webhook:artifacts:config=config/base/webhook
bin/kustomize build config | kubectl apply -f -
namespace/kafka created
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
customresourcedefinition.apiextensions.k8s.io/kafkaclusters.kafka.banzaicloud.io configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
customresourcedefinition.apiextensions.k8s.io/kafkatopics.kafka.banzaicloud.io configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
customresourcedefinition.apiextensions.k8s.io/kafkausers.kafka.banzaicloud.io configured
./scripts/image_patch.sh "config/overlays/specific-manager-version/manager_image_patch.yaml" banzaicloud/kafka-operator:chart/kafka-operator/0.2.9
kustomize build config/overlays/specific-manager-version | kubectl apply -f -
customresourcedefinition.apiextensions.k8s.io/kafkaclusters.kafka.banzaicloud.io configured
customresourcedefinition.apiextensions.k8s.io/kafkatopics.kafka.banzaicloud.io configured
customresourcedefinition.apiextensions.k8s.io/kafkausers.kafka.banzaicloud.io configured
role.rbac.authorization.k8s.io/kafka-operator-certman-proxy-leader-election-role created
clusterrole.rbac.authorization.k8s.io/kafka-operator-certman-proxy-manager-role created
clusterrole.rbac.authorization.k8s.io/kafka-operator-certman-proxy-proxy-role created
rolebinding.rbac.authorization.k8s.io/kafka-operator-certman-proxy-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/kafka-operator-certman-proxy-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/kafka-operator-certman-proxy-proxy-rolebinding created
service/kafka-operator-certman-proxy-alertmanager created
service/kafka-operator-certman-proxy-controller-manager-metrics-service created
service/kafka-operator-certman-proxy-webhook-service created
deployment.apps/kafka-operator-certman-proxy-controller-manager created
certificate.cert-manager.io/kafka-operator-certman-proxy-serving-cert created
issuer.cert-manager.io/kafka-operator-certman-proxy-selfsigned-issuer created
validatingwebhookconfiguration.admissionregistration.k8s.io/kafka-operator-certman-proxy-validating-webhook-configuration created

**Expected behavior**
./scripts/image_patch.sh "config/overlays/specific-manager-version/manager_image_patch.yaml" banzaicloud/kafka-operator:chart/kafka-operator/0.2.9
# expect use the right image name and tag

**Additional context**
today git clone the source
today install the GoLang
go version go1.13.4 linux/amd64
Linux k8s-tcm1 4.4.184-1.el7.elrepo.x86_64 #1 SMP Thu Jun 27 08:30:47 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 7.6.1810 (Core)

**Comment by baluchicken** [comment]
Thanks for reporting this, we are going to investigate this and get back with our findings

**Comment by baluchicken** [comment]
We found the bug going to fix this soon.

**Comment by seecsea** [comment]
it works ok，thanks
