### ISSUE TITLE
Cross-namespace owner reference

### ISSUE THREAD

**Issue by qbast** [banzaicloud/kafka-operator#229]
**Describe the bug**

Kafka operator creates a certificate named kafka-ca-certificate in cert-manager namespace. That certificate has ownerReference set to a KafkaCluster object from another namespace.  Also after cert-manager reconciles the certificate and creates a secret, the operator assigns cluster ownership to this secret as well.
This randomly triggers bug https://github.com/kubernetes/kubernetes/issues/65200 . 
In my case it caused garbage collector to delete CA certificate, server certificate and pods.  

**Steps to reproduce the issue:**

Install kafka cluster with TLS enabled, wait long enough (in my case the bug happened after 3 weeks). 

**Expected behavior**

Do not set ownerReference on CA certificate and secret. 

**Screenshots**

**Additional context**

The problem is present in both master and 0.7 branches. Tested on GKE 1.14.

**Comment by tinyzimmer** [comment]
I thought this was taken care of earlier, but sure enough I just looked and see where it got left behind for that. I'll open a PR soon because its just taking a few lines out.

**Comment by thomasjardin** [comment]
Hello,

**Comment by thomasjardin** [comment]
Hello

**Comment by thomasjardin** [comment]
Hello, we faced a few days ago a complete Kafka cluster deletion, initiated by the Kub garbage collector.
After investigation, we found that one of the two cluster-scoped `ClusterIssuers` created by the operator had triggered the [Kub#65200](https://github.com/kubernetes/kubernetes/issues/65200) bug.
As stated by @tinyzimmer in #230, that fix still leaves an *ownerReference* on the `ClusterIssuer`. 

Do you plan to fix the same way the `ClusterIssuer` objects to avoid complete cluster teardown?

**Comment by baluchicken** [comment]
Thanks for reporting this @thomasjardin we are going to fix this ASAP.

**Comment by baluchicken** [comment]
@thomasjardin this PR https://github.com/banzaicloud/kafka-operator/pull/579 fixes the error.

**Comment by thomasjardin** [comment]
Thanks @baluchicken!
