### ISSUE TITLE
Cannot create resource KafkaTopic with replication factor higher than number of brokers (brokers are initializing)

### ISSUE THREAD

**Issue by borisputerka** [banzaicloud/kafka-operator#231]
**Describe the bug**
When I want to use creation of kafka cluster in CI/CD I have this problem: creating kafkatopics alongside kafka cluster is giving this error:

`messages/KafkaTopic: Error from server (BadRequest): error when creating "STDIN": admission webhook "kafkatopics.kafka.banzaicloud.io" denied the request: Replication factor is larger than the number of nodes in the kafka cluster`

I understand why it gives me this error, but wouldn't be better if the operator handles this and wait for all brokers to startup? Those brokers where up in few seconds later and was possible to rerun the pipeline.

**Comment by tinyzimmer** [comment]
So if the admission webhook (what gave you that error) didn't exist, the topic CR would get created and the operator would go into an error loop trying to create the topic. In your case, when the brokers become actually available, this would settle itself.

However, there is also the case where a user actually makes a mistake in their replication factor. It's better to get feedback early then to wonder where your topic is, and then have to go search the operator logs to find out you made a mistake.

Off the top of my head I can't think of a way to address this without adding too much complexity to the code.
