### ISSUE TITLE
Is it possible to scale cluster up / down?

### ISSUE THREAD

**Issue by smiklosovic** [banzaicloud/kafka-operator#241]
Hi,

we are evaluating this project and we would like to know what it takes to scale up and down a Kafka cluster. From the source code it just checks if a pod should be deleted (1) but how does it exactly work?

I read the docs and there is a reference to Linkedin's cruise control project but I am struggling to understand what it all means when it comes to scaling up / down.

Hence, is there some example how to scale up / down and how would one go around that?

Regards

(1) https://github.com/banzaicloud/kafka-operator/blob/master/pkg/resources/kafka/kafka.go#L159-L160

**Comment by stoader** [comment]
The Kafka cluster is being managed by the operator based on the config stored in `KafkaCluster` customer resource. This CR contains the list of brokers that makes up the cluster. (as an example see: https://github.com/banzaicloud/kafka-operator/blob/master/config/samples/simplekafkacluster.yaml#L26-L32)

You can add/remove brokers manually by editing the `brokers` section of the `KafkaCluster` CR. The operator will notice that the CR has changed and takes care of starting / terminating broker pods. Also beside starting/terminating brokers pods it engages CruiseControl to notify it that a new broker was created or one is about to be removed. Cruise control will take care of steps that ensure graceful addition / removal of a broker (e.g. performs rebalancing)

Beside adding / removing brokers manually the `kafka-operator` is capable to autoscale the Kafka cluster based on metrics. This functionality requires having Prometheus and the appropriate alert rules set up (as example of such alert definitions see: https://github.com/banzaicloud/kafka-operator/blob/master/config/samples/example-prometheus-alerts.yaml)
