### ISSUE TITLE
RackAwareness configuration is lost upon cluster upgrade

### ISSUE THREAD

**Issue by amuraru** [banzaicloud/kafka-operator#256]
**Describe the bug**
Rack awareness settings are lost upon cluster upgrade. 
**Steps to reproduce the issue:**

- create a brand new cluster using operator 0.9.0
- broker.rack is correctly set in ConfigMap and server.propertiers
- trigger a rolling upgrade (update cluster CR)
- upgrade is perfomed but at the end the broker.rack is not set anymore

**Expected behavior**
Rack awareness should be maintained across cluster upgrades

**Comment by stoader** [comment]
Can you describe how did you trigger the rolling upgrade? Did you apply a modified KafkaCluster CR definition onto existing CR or patched the existing CR?

**Comment by amuraru** [comment]
@stoader Updated the yaml locally and `k apply -f`

**Comment by stoader** [comment]
Did you copied the rack  setting under each broker readonly config (which contains the rack info) from the CR into the local yaml file? If not than the these will be removed as the local yaml that was applied didn't have these.

**Comment by amuraru** [comment]
Ok - understood now the issue. @baluchicken mentioned that should be fixed. Thanks
