### ISSUE TITLE
Issue using existing Prometheus

### ISSUE THREAD

**Issue by AceHack** [banzaicloud/kafka-operator#261]
When trying to use an existing kafka alert manager I get the following from the Kafka alert manager.  I feel like it's looking in the wrong namespace or something like that, any suggestions?

KafkaCluster.kafka.banzaicloud.io \"kafka\" not found\ncould not get cr from k8s\ngithub.com/banzaicloud/kafka-operator/pkg/k8sutil.GetCr\n\t/workspace/pkg/k8sutil/cr.go:120
github.com/banzaicloud/kafka-operator/internal/alertmanager/currentalert.(*examiner).getCR\n\t/workspace/internal/alertmanager/currentalert/process.go:40
github.com/banzaicloud/kafka-operator/internal/alertmanager/currentalert.(*examiner).examineAlert\t/workspace/internal/alertmanager/currentalert/process.go:54
github.com/banzaicloud/kafka-operator/internal/alertmanager/currentalert.(*currentAlerts).HandleAlert\t/workspace/internal/alertmanager/currentalert/current_alerts.go:132
github.com/banzaicloud/kafka-operator/internal/alertmanager/dispatcher.Dispatcher
\t/workspace/internal/alertmanager/dispatcher/dispatcher.go:44
github.com/banzaicloud/kafka-operator/internal/alertmanager/receiver.alertReciever\t/workspace/internal/alertmanager/receiver/receiver.go:33
github.com/banzaicloud/kafka-operator/internal/alertmanager/receiver.(*HTTPController).reciveAlert\t/workspace/internal/alertmanager/receiver/http_handler.go:59
net/http.HandlerFunc.ServeHTTP\t/usr/local/go/src/net/http/server.go:2007
net/http.(*ServeMux).ServeHTTP\t/usr/local/go/src/net/http/server.go:2387
net/http.(*ServeMux).ServeHTTP\t/usr/local/go/src/net/http/server.go:2387
net/http.serverHandler.ServeHTTP\t/usr/local/go/src/net/http/server.go:2802
net/http.(*conn).serve\t/usr/local/go/src/net/http/server.go:1890
runtime.goexit\t/usr/local/go/src/runtime/asm_amd64.s:1357","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
github.com/banzaicloud/kafka-operator/internal/alertmanager/dispatcher.Dispatcher\t/workspace/internal/alertmanager/dispatcher/dispatcher.go:46
github.com/banzaicloud/kafka-operator/internal/alertmanager/receiver.alertReciever\t/workspace/internal/alertmanager/receiver/receiver.go:33
github.com/banzaicloud/kafka-operator/internal/alertmanager/receiver.(*HTTPController).reciveAlert\t/workspace/internal/alertmanager/receiver/http_handler.go:59
net/http.HandlerFunc.ServeHTTP\t/usr/local/go/src/net/http/server.go:2007
net/http.(*ServeMux).ServeHTTP\t/usr/local/go/src/net/http/server.go:2387
net/http.(*ServeMux).ServeHTTP\t/usr/loca/go/src/net/http/server.go:2387
net/http.serverHandler.ServeHTTP\t/usr/local/go/src/net/http/server.go:2802
net/http.(*conn).serve\t/usr/local/go/src/net/http/server.go:1890

**Comment by stoader** [comment]
What namespace is your KafkaCluster CR in? Also, what is the name of your KafkaCluster CR?

**Comment by stoader** [comment]
Kafka operator expects two labels `kafka_cr` and `namespace` to be on each alert it receives in order to be able to identify the Kafka cluster the alert is for.

Please check your Prometheus relabelling expressions whether these apply `kafka_cr` to the alerts  as in this example https://github.com/banzaicloud/kafka-operator/blob/master/config/samples/kafkacluster-prometheus.yaml#L34-L39

**Comment by AceHack** [comment]
So that just set's the kafka_cr how does the namespace get set on the alert?

**Comment by VishwasKumar** [comment]
@stoader We are running the `kafka` cluster in the `kafka` namespace
`
kubectl get kafkacluster -n kafka
NAME    AGE
kafka   47h
`
I can confirm that the operator responds to the alerts correctly when I add the namespace label onto the `PrometheusRule` just to confirm @AceHack' suspicion

**Comment by VishwasKumar** [comment]
@stoader we had the `kafka` cluster in the `kafka` namespace.
```bash
kubectl get kafkacluster --all-namespaces
NAMESPACE     NAME       AGE
kafka                  kafka        2d
```

**Comment by stoader** [comment]
@AceHack can you check the relabelling config for `role: pod` of your Prometheus instance  for something like:
```
- source_labels: [__meta_kubernetes_namespace]
   action: replace
   target_label: .....```

and verify what value is set for `target_label`?

**Comment by stoader** [comment]
@AceHack any update on how the relabelling rule look like in your Prometheus config?

**Comment by AceHack** [comment]
Relabeling fixed my issue, thanks.
