### ISSUE TITLE
Cluster manual upscale fails when broker ids are not consecutive

### ISSUE THREAD

**Issue by amuraru** [banzaicloud/kafka-operator#263]
**Describe the bug**
I have a KafkaCluster definition with 4 brokers: 0,1,2,3 
I am trying to add manually 3 new brokers but not consecutive, i.e. skipping 2 brokers ids 0, 1, 2, 3, 6, 7, 8
In this case the upscale is stuck and the operator spits continuously:
```
{"level":"info","ts":1580117837.8854675,"logger":"controllers.KafkaCluster","msg":"cruise control communication error during upscaling broker id: 7 (broker is not ready yet)"
```
**Expected behavior**
Upscale should work regardless of broker ids selection

**Additional context**

Looking through the code it seems that the culprit is the way the operator checks for broker id readiness in CC:
https://github.com/banzaicloud/kafka-operator/blob/e24626646ea214ea47fa8b397f646a6aff3442f9/pkg/scale/scale.go#L159

IIUC the number of brokers reported by CC in `kafka_cluster_state` should the same as the next broker-id, thus assuming the broker ids are always consecutive.
It would be better to check the actual broker id in the returned response.

**Comment by amuraru** [comment]
Checking CC it seems that there is more reliable way of checking the broker readiness in CC: `kafkacruisecontrol/load` API:
`response.brokers[<seq>].BrokerState`

**Comment by baluchicken** [comment]
Thanks for reporting this, we already identified this problem and planning to release a new version of the operator later today which fixes this as well.
