### ISSUE TITLE
GetCruiseControlStatus is too strict when adding/upscaling cluster

### ISSUE THREAD

**Issue by amuraru** [banzaicloud/kafka-operator#264]
**Describe the bug**

Currently the CC status in GetCruiseControlStatus is checking `isProposalReady=true` in `/state` CC endpoint
During a testing on one of my cluster I ended up with 3 brokers that happened to be on a single AZ. While kafka was still running, CruiseControl could not build a proposal out of the configured `hard.goals` that inclued RackAwareGoal. This is expected from CC perspective as a hard goal was violated (i.e. not enough racks) and  reports  `isProposalReady=false`

In turn I tried to fix the "issue" by adding more brokers in the other 2 AZs/racks. 
But the operator is still checking `GetCruiseControlStatus` and thus cannot add/scale the cluster.

**Expected behavior**

When adding brokers the CC check should be less restrictive in terms of rebalancing proposal availablity. Instead it should check if CC is working/receiving monitoring data and allow new brokers to be added.

**Comment by baluchicken** [comment]
Thanks for reporting this issue, `GetCruiseControlStatus` should not affect scaling the cluster. In case of a new broker the operator first creates the Kubernetes resources(pod, configmap, pvc, service). In the next step it tries to add it gracefully. If the CC is not ready yet, (it needs like 10 minutes in a new cluster to be able to generate new proposals) the operator tries to talk to it by checking its analyser state. And if it becomes ready it tries to add those brokers gracefully.

I tested this in a following way:
I created a fresh cluster where the CC is not ready `isProposalReady=false`. Then I initiated an upscale with the operator and it succeeded. The brokers are in `GracefulUpscaleRequired` state but they are running. Once the CC becomes available the operator will try to add them gracefully.

**Comment by amuraru** [comment]
@baluchicken 

> The brokers are in GracefulUpscaleRequired state but they are running. Once the CC becomes available the operator will try to add them gracefully.

That's my understanding as well, however in our setup we configure RackAwareGoal as a hard goal in CC so CC will not be able to generate the proposal in this case and brokers will never be added/registered in CC.

Let me try to simplify the scenario:

- start with a cluster of 3 brokers, rackawareness enabled, one broker per each rack
- configure RackAwareGoal as a hard goal in CC config
- create a topic with 1 partition.  RF=3
- you loose one rack (hard kill the pod in rack 3 say)
Partition  will be under-replicated (2 replicas)
But because the rackawaregoal is a hard goal in CC there is no proposal plan that can satisfy that - hence it will stay in isProposal=false

Alert is triggered, AZ/rack recovers and kafka-operator will reschedule the pod In that rack/broker-group, broker will join kafka and operator will mark it as GracefulUpscaleRequired and waiting for isProposal=true before triggering the add_broker in CC.
Again CC cannot generate a proposal as the RackAwareGoal is violated as there is No broker in rack3 registered in CC.
Hence the "deadlock" - chicken and the egg situation

In tbis case the operator should verify if broker is READY (broker state?) and issue add_broker straight away
