### ISSUE TITLE
Strange resource usage by operator

### ISSUE THREAD

**Issue by borisputerka** [banzaicloud/kafka-operator#287]
**Describe the bug**
Kafka operator has some strange resource usage. Over time it consumes more and more ram (which also reflects in more and more cpu usage,network usage and disk usage. After some time it is restarted.

[Screenshot](https://drive.google.com/file/d/1zfiWglmxk-VhHwtcqmxnYb9d2mgASjfg/view?usp=sharing)

**Comment by baluchicken** [comment]
Thanks for reporting this we are going to investigate this and get back to you with our findings

**Comment by stoader** [comment]
@borisputerka this has been addressed in the latest release. If you still see this issue with the latest release just re-open this issue.
