### ISSUE TITLE
Support for Kafka Connect

### ISSUE THREAD

**Issue by disha98** [banzaicloud/kafka-operator#312]
**Is your feature request related to a problem? Please describe.**
No current support for Kafka Connect 

**Additional context**
Kafka Connect framework itself is part has Apache 2.0 license. Only the Confluent supported plugins are Confluent Community licensed. So we should be able to add support for Kafka Connect without any other additional license? 

If anyone could please help me with more information about this soon!

With reference to #109

**Comment by disha98** [comment]
@baluchicken @stoader

**Comment by matyix** [comment]
Kafka connect framework is already natively supported by Kafka (https://kafka.apache.org/documentation/#connect) and the operator - it’s the plugins which might fall under licensing. For example in [Supertubes](https://banzaicloud.com/products/supertubes/) we use Mirror Maker 2 which uses Connect behind the scene. We don’t indent to add plugins to the operator, but you can just do that fine.

For Kafka Connect reference, see the `/opt/kafka/bin/connect-standalone` in the Docker image.
