### ISSUE TITLE
Incompatibility with global priority classes

### ISSUE THREAD

**Issue by SapientGuardian** [banzaicloud/kafka-operator#316]
**Describe the bug**
The Kafka operator fails to spin up brokers on a cluster with global default priorities enabled, because it attempts to force a priority of 0 in the pod spec.

**Steps to reproduce the issue:**
1. Create a global default priority class
```
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: global-default-priority
value: 100000
globalDefault: true
description: "This is the standard priority class for all pods"
```
2. Create a Kafka cluster with https://github.com/banzaicloud/kafka-operator/blob/master/config/samples/simplekafkacluster.yaml

3. Observe that no broker pods are created, and entries like the following are logged from the operator manager pod:

```
{
   "level":"error",
   "ts":1583503421.3124266,
   "logger":"controller-runtime.controller",
   "msg":"Reconciler error",
   "controller":"KafkaCluster",
   "request":"pushdelivery-candidate/pushdelivery-kafka",
   "error":"creating resource failed: pods \"pushdelivery-kafka-0-\" is forbidden: the integer value of priority (0) must not be provided in pod spec; priority admission controller computed 100000 from the given PriorityClass name",
   "stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:192\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88"
}
```

**Expected behavior**
Broker pods should spin up with the global default priority

**Additional context**
The offending line of source appears to be https://github.com/banzaicloud/kafka-operator/blob/f436d8ba36e6212b6d421cd2c8658a12aea49075/pkg/resources/kafka/pod.go#L227

I imagine the simple removal of that line would solve this problem, but I'm not sure what the intent was of putting it there in the first place.

**Comment by baluchicken** [comment]
Thanks for opening this. We are going to fix this ASAP. 
This part remained there from an earlier version of the operator, but currently not in use any more.

**Comment by baluchicken** [comment]
@SapientGuardian The fix just got merged.

**Comment by SapientGuardian** [comment]
Thanks for the quick fix! Is a new docker image going to get published for this, or is it going to be included in a later release? And if the latter, is there a schedule for that?

**Comment by baluchicken** [comment]
It is going to be included in a later release, which will be released soon.
In the meantime you can use the following command to build your own docker image from master.
`IMG=<your-image-name-here> make docker-build`
