### ISSUE TITLE
Align kafka broker jmx_exporter configs with upstream 

### ISSUE THREAD

**Issue by amuraru** [banzaicloud/kafka-operator#318]
**Is your feature request related to a problem? Please describe.**
Currently operator defines a custom mapping jmx_exporter configuration for kafka jmx metrics.
https://github.com/banzaicloud/kafka-operator/blob/d371ad1/api/v1beta1/kafkacluster_types.go#L523-L611

jmx_exporter upstream also maintains a list of mappings which seems more generic: 
https://github.com/prometheus/jmx_exporter/blob/master/example_configs/kafka-2_0_0.yml

**Describe the solution you'd like to see**
Would it make sense to adopt the vanilla configuration upstream?

**Describe alternatives you've considered**
Overriding this is possible per Kafka CR but cumbersome and hard to maintain.

**Comment by baluchicken** [comment]
We just merged the PR which adopts the vanilla configuration from upstream.
