### ISSUE TITLE
Kafka broker pods are recreated in a loop

### ISSUE THREAD

**Issue by amuraru** [banzaicloud/kafka-operator#320]
**Describe the bug**
In one of our test environments we see the kafka broker pods being recreated by the operator without any change being performed on cluster spec.

**Steps to reproduce the issue:**
Hard to reproduce but it seems to manifest in k8s environments where multiple api servers are serving k8s API and multiple disks are attached to brokers

**Expected behavior**
Pods are bounced only when actual change applied to cluster spec.

**Screenshots**
Looking deeper in the operator logs it seems that the change is triggered by the order in which the broker PVCs [are listed during reconcile](https://github.com/banzaicloud/kafka-operator/blob/963e01a/pkg/resources/kafka/kafka.go#L100-L107) which may not be a stable order all the times:
![image](https://user-images.githubusercontent.com/728853/76360719-39ed9500-6326-11ea-98a6-7f8b6e624e59.png)

**Comment by pashafirdous** [comment]
Hi,

Facing the same issue.

please let me know the fix.

regards,
Pasha
