### ISSUE TITLE
banzai kafka operator is neither a k8s deployment nor a statefulset ?

### ISSUE THREAD

**Issue by kaushiksrinivas** [banzaicloud/kafka-operator#324]
We see in the docs that, the kafka banzai operator is quoted as a deployment and statefulset.
But looking at the operator code, we see there is no k8s Kind "Deployment" object created anywhere for kafka, instead pods and related resources are created and managed independently using the k8s APIs.

Why do we still say kafka banzai operator as a deployment ? Instead is it neither kind k8s "Deployment or Statefulset" and is independently managed by kafka operator itself as such ?

**Comment by matyix** [comment]
>Why do we still say kafka banzai operator as a deployment ? Instead is it neither kind k8s "Deployment or Statefulset" and is independently managed by kafka operator itself as such ?

It’s not clear whether you are referring to the Kafka operator or the Kafka cluster the operator deploys, but I hope you are aware these are two different things. Also, not sure from where you get any of the claims (`Why do we still say...`) but let me clarify a few things:

The operator itself is a Deployment (check out Kubebuilder, which from 0.2 switched from StatefulSet to Deployment).

The Kafka cluster, as stated in the Readme, of you read it carefully it’s not a StatefulSet for several reasons but is a Pod.

**Comment by kaushiksrinivas** [comment]
Hi @matyix 
I was referring to kafka cluster, sorry for quoting it wrongly as kafka operator. Thank you so much for the response.
