### ISSUE TITLE
Evicted pods are not recreated

### ISSUE THREAD

**Issue by qbast** [banzaicloud/kafka-operator#326]
**Describe the bug**
Two of three kafka broker pods have been evicted by kubernetes. Operator leaves the cluster in this state (one broker running, two down) instead of recreating the evicted pods.

**Steps to reproduce the issue:**
Create a cluster with 3 brokers. Force eviction of any pod.

**Expected behavior**
I would expect that operator notices evicted pods and creates replacements.

**Additional context**
Observed with operator version 0.10.0 , kubernetes 1.15 on GKE.

**Comment by stoader** [comment]
@qbast can you attach kafka-operator logs as well as you kafkacluster cr? What triggered the eviction of the pods?

**Comment by qbast** [comment]
Hello

Log and cr attached:
[kafkacluster.yaml.txt](https://github.com/banzaicloud/kafka-operator/files/4338042/kafkacluster.yaml.txt)

[manager.log](https://github.com/banzaicloud/kafka-operator/files/4338044/manager.log)

This is a dev cluster, so there are other pods on the same node. Eviction was triggered during load test when one of other services started using lots of memory. Then Kafka's usage increased as well and the node ran out of memory which required eviction.

**Comment by stoader** [comment]
Logs do not show any errors that would explain why pods are not recreated. The operator acts as though those evicted pods are still there thus is not aware that it has to create new ones. Are those pods are still there or were cleaned up by Kubernetes?

**Comment by qbast** [comment]
The pods were still there after about 10h. Then I deleted them manually.

**Comment by stoader** [comment]
After deleting them manually did the operator re-create those pods?

**Comment by qbast** [comment]
Yes. Pretty much immediately.
