### ISSUE TITLE
Need information on cruise control integration with banzai operator.

### ISSUE THREAD

**Issue by kaushiksrinivas** [banzaicloud/kafka-operator#341]
From operator code, we understand below aspects for example
A kafka pod is down, watch triggers the reconcile and the pod spec object is created from the reconcile kafka operator code.

We also see integration with cruise control, which also states cruise control does
 self-healing for the Kafka cluster when Broker failure detection.

Now little confused, if kafka pod failure is taken care of by the banzai operator reconcile code or from the cruise control's functionality ?
Is cruise control used to improve any specific use case handling  ?

Thanks in advance.

**Comment by stoader** [comment]
CC is tracking the Kafka cluster's state and when notices that pre-configured goals can not be met due to broker failures or infra issues it can execute various tasks such as rebalancing etc in order to meet those goals.

**Comment by kaushiksrinivas** [comment]
Hi @stoader 
So if i understand correctly, broker pod addition/deletion is taken care of by the kafka operator code.
And when for example a kafka broker is removed by modifying the kafkaCluster CR, then the operator code will delete the pod/pvc/headlessSvc/configMap related to that broker. 
Then are we using the cruise control to move the partitions owned by the broker which is brought down now to one of the existing available brokers doing a rebalance from cruise control ?

Also can you please provide some information on the "pre-configured goals for CC" which you have mentioned for kafka operator ? specifically can we look at the list of goals defined somewhere ?

Thank you so much in advance.

**Comment by baluchicken** [comment]
@kaushiksrinivas You are right, the operator uses the CC exactly how you explained.
You can see the list of the goals in the sample cluster CRs. Those are available [here](https://github.com/banzaicloud/kafka-operator/blob/e27521ef5939317cc90c4cb2b1e9d2033434408d/config/samples/simplekafkacluster.yaml#L52)

**Comment by kaushiksrinivas** [comment]
Thank you for the quick confirmation.
