### ISSUE TITLE
Operator does not notice missing CC topic

### ISSUE THREAD

**Issue by qbast** [banzaicloud/kafka-operator#343]
**Describe the bug**

At some point KafkaTopic object for CC automatically created by the operator vanished (no idea why). This leads to cruisecontrol pod going into a crash loop.  KafkaCluster status is:

Status:
  Alert Count:  0
  Brokers State:
    0:
      Configuration State:  ConfigInSync
      Graceful Action State:
        Cruise Control State:  GracefulUpscaleSucceeded
        Error Message:         CruiseControl not yet ready
      Rack Awareness State:    broker.rack=europe-west3,europe-west3-c
 ... 
  Cruise Control Topic Status:  CruiseControlTopicReady

So it notices that CC has a problem but not that the CC topic is the problem.

**Steps to reproduce the issue:**

Create a cluster. Do kubectl delete kafkatopic kafka-cruise-control-topic . 

**Expected behavior**

Operator notices that CC topic is not ready and recreates it.

**Additional context**
Tested on operator version 0.10

**Comment by balazsbc** [comment]
Hi @qbast, thank you for bringing this to our attention, we are going to check it out soon.

In the meantime, would you mind adding your company to the ADOPTERS.md in case you are using the operator in production? https://github.com/banzaicloud/kafka-operator/blob/master/ADOPTERS.md Thanks!
