### ISSUE TITLE
Need information on the Reconciler implementation.

### ISSUE THREAD

**Issue by kaushiksrinivas** [banzaicloud/kafka-operator#344]
Am trying to understand the code base.
Below is my understanding/query.

KafkaClusterReconciler implements the actual Reconciler interface,
with function "Reconcile(Request) (Result, error)"
and is called upon every change on the watches registered.

And inside this reconcile, in a nested manner calls to envoy,istioingress,kafka etc.. reconcile functions are being called..
If looked at kafka.go from resources, implements ComponentReconciler.
So is this interface and its function naming created in a way to maintain a similar design/naming as provided by the controller-runtime Reconciler interface ?

My understanding is, if any events due to watches registered, reconcile requests are landing at KafkaClusterReconciler and in a nested manner (using ComponentReconciler, and having the same named function Reconcile in the interface) every sub component's reconcile logic has been put up and is orchestrated by the KafkaClusterReconciler's Reconcile code.

Your inputs would help a lot.
Thanks in advance.

**Comment by kaushiksrinivas** [comment]
@baluchicken @stoader 
Can you provide some inputs on the query.
Thanks lot

**Comment by baluchicken** [comment]
You are right. The KafkaClusterReconciler's does exactly that.

**Comment by kaushiksrinivas** [comment]
Thank you @baluchicken
