### ISSUE TITLE
Is it possible to set custom env variables? i.e JMX_PORT

### ISSUE THREAD

**Issue by kirecek** [banzaicloud/kafka-operator#351]
**Is your feature request related to a problem? Please describe.**
Hello, i would like to collect JMX metrics ourselves since we are using different monitoring stack (DD). Is it possible to somehow configure environment variables and set [JMX_PORT](https://github.com/kafka-dev/kafka/blob/master/bin/kafka-run-class.sh#L38)? I was not able to find anything in docs.

**Describe the solution you'd like to see**
Maybe add `env` block to kafka cluster spec or extend monitoring config ---something like this? https://github.com/banzaicloud/kafka-operator/pull/352

**Describe alternatives you've considered**
Currently, we are using custom images which have set the mentioned env variable.

**Comment by baluchicken** [comment]
Closing this since the PR got merged.
