### ISSUE TITLE
Correctly delete Kafka without deleting topics

### ISSUE THREAD

**Issue by Lirt** [banzaicloud/kafka-operator#363]
Hello Banzai,

I would like to ask you for a guidance to delete Kafka Cluster and Topic resources without actually deleting them (delete only resources, not actual topics in kafka/zookeeper). 

My goal is to migrate kafka cluster to new kubernetes cluster without deleting any zookeeper configuration, any kafka configuration, any topics or any data.

What I tried and failed with:
- If I delete `kafkaclusters` resource, operator deletes topics.
- If I delete `kafkatopics` resource, operator deletes topics.
- Same happens if I remove validating webhook before removing any Kafka resources. 
- If I delete finalizer from topic, it could work, but operator immediately adds finalizer again to it, so it is unusable.
- If I delete Zookeeper before Kafka, operator gets stuck at deleting resources.
- If I delete operator, I can delete pods, but I cannot delete Kafka resources.

How I succeeded:
1. Delete validating webhook.
1. Delete zookeeper (I keep disks).
1. Remove finalizers from kafkaclusters and kafktopics.
1. Delete kafka cluster (I keep disks).
1. Delete all kafka topics.

This way all data stays in zookeeper and kafka correctly, but after restarting kafka in new cluster, it does `Recovering unflushed segment`. That means Kafka haven't been shut down cleanly, which could be because:

- Zookeeper was deleted before Kafka.
- Some configuration parameter is missing (I use `controlled.shutdown.enable=true`).
- Some lifecycle hook is missing and k8s doesn't let pod shutdown gracefully.

Can you please help and lead me how to do this clean? I think this could also be noted in documentation if anybody wanted to migrate as well.

If you need more information, please leave me a comment.

Edit: I am currently using kafka operator version `0.8.1`.

**Comment by stoader** [comment]
@Lirt  you can migrate your Kafka cluster to another one with using MM2 deployed by [Supertubes](https://banzaicloud.com/docs/supertubes/cli/reference/supertubes_mirror-maker2/)

**Comment by stoader** [comment]
@Lirt  you can migrate your Kafka cluster to another one in a clean way with  [Supertubes](https://banzaicloud.com/docs/supertubes/cli/reference/supertubes_mirror-maker2/)

**Comment by Lirt** [comment]
@stoader Thanks, but I'd like to perform this with kafka-operator solely with low-level operations, co I can have control on it.

**Comment by stoader** [comment]
@Lirt back to your original question

> Can you please help and lead me how to do this clean

The process you described above seem rather hacky. Our recommendation to do it in a clean way is to use MirrorMaker2.

**Comment by Lirt** [comment]
Well my approach isn't good, but I don't know how to do it otherwise. 

There must be simple way to just shutdown kafka.

**Comment by Lirt** [comment]
OK, so I found a way to do it and it is simple, just set `brokers: []` in `kafkacluster` resource.

Closing as resolved. If you think this is useful to have in documentation, I can do PR.
