### ISSUE TITLE
Upgrade jmx_exporter to 0.13

### ISSUE THREAD

**Issue by amuraru** [banzaicloud/kafka-operator#392]
**Is your feature request related to a problem? Please describe.**
Current kafka-operator is using jmx_exporter v0.12 which is already couple of years old :)
Recently jmx_exporter 0.13 has been released so I propose we pick up this new version.

**Describe the solution you'd like to see**
On top of upstream jmx_exporter 0.13 I added in my fork https://github.com/amuraru/jmx_exporter/commits/java-11 :
- compile using java-11 and upgrade dependencies
- build docker file

Would be possible for you guys to review this and build a docker image with this version?

**Describe alternatives you've considered**
Use our own image and override this in KafkaCluster spec but I think the entire community here should benefit if we make this the default.

**Comment by baluchicken** [comment]
Thanks @amuraru we will investigate and bump the jmx_exporter to version 0.13.
