### ISSUE TITLE
Sometimes the KafkaUser CR can come into a weird state where the CR is being deleted before it got the chance to create credentials.

### ISSUE THREAD

**Issue by alexvanboxel** [banzaicloud/kafka-operator#414]
**Describe the bug**
Sometimes the KafkaUser CR can come into a weird state where the CR is being deleted before it got the chance to create credentials. If the delete state is a result of a namespace deletion the finalize step never happens because it tries to reconcile till the credentials are being created, but they can't be created because the namespace is being deleted. (PR is upcoming)

**Steps to reproduce the issue:**
- Create a stress test where you create a lot of namespaces with KafkaUser and KafkaTopic
- Start deleting the namespaces before the creation process is finished
- You will notice the that the namespaces will be in Terminating state forever because of the KafkaUser CR

**Expected behavior**
When no credentials can be created and the CR is in deletion state remove the finalizer

**Comment by baluchicken** [comment]
Thanks @alexvanboxel we just merged this. We would like to ask if you like the operator please add your company to our [Adopters](https://github.com/banzaicloud/kafka-operator/blob/master/ADOPTERS.md) file. Thanks
