### ISSUE TITLE
Kafka Operator reconcile when pods are deleted manually.

### ISSUE THREAD

**Issue by britoaldan** [banzaicloud/kafka-operator#418]
we see the kafka reconcile logic of the broker pods happening when the pod is either added/removed through the change in crd's.
what happens when we delete the pod manually say using "_kubectl delete pod <pod-name>_"
does the same reconcile logic hold good ?
can you please point out some references to the code which does this or handles this scenario?

**Comment by stoader** [comment]
@britoaldan yes pods will be re-created by the reconcile logic.

**Comment by britoaldan** [comment]
hi @stoader,
are u referring to this piece of code ?
in kafka.go
// Handle Pod delete
err := r.reconcileKafkaPodDelete(log) 

if not can you provide the code or file reference.

**Comment by britoaldan** [comment]
hi @baluchicken, @stoader, 

can you please provide insights on where the pod watches are done, when the kafka broker is manually deleted 
using kubectl delete command and where the re-concile happens for the same ?

**Comment by stoader** [comment]
The deletion of broker pods and resources used by it (e.g. in case of cluster downscale) is handled by https://github.com/banzaicloud/kafka-operator/blob/master/pkg/resources/kafka/kafka.go#L180

The adding/updating of broker pods is handled by https://github.com/banzaicloud/kafka-operator/blob/master/pkg/resources/kafka/kafka.go#L279

Regarding watching pods https://book.kubebuilder.io/quick-start.html is used under the hood. I'd recommend familiarise yourself with Kubebuilder first to be able to understand how kafka-operator is implemented.

Can you describe your use case that you want to achieve that requires you to have a deep understanding of the kafka-operator implementation?

**Comment by britoaldan** [comment]
Hi @stoader, 
Thanks for the detailed description.
was browsing the code and wanted to understand more on how the accidental delete of the pod is handled.
