### ISSUE TITLE
Need information about rolling upgrade of kafka cluster.

### ISSUE THREAD

**Issue by kaushiksrinivas** [banzaicloud/kafka-operator#419]
As per the doc 
https://banzaicloud.com/blog/kafka-rolling-upgrade/

We see rolling upgrade is achieved in banzai via super tubes.
And description highlights about static and dynamic property update for kafka.

From the code reading on banzai kafka, observed that dynamic reconfig is triggered via 
func (r *Reconciler) reconcilePerBrokerDynamicConfig which is using "sarama" client to update the dynamic configs without needing a broker restart.

Can you please throw some light on updating the static properties like zk connect url. ?
Is the rolling upgrade supported in kafka operator when updating a static config property (Does one have to install super tubes seperately as a pre req for kafka operator installation ?)?

Thanks in advance,
Kaushik.

**Comment by kaushiksrinivas** [comment]
Hi @stoader @baluchicken 
Need your inputs.
Thanks,
Kaushik.

**Comment by kaushiksrinivas** [comment]
I see 
err = r.Client.Delete(context.TODO(), currentPod) in the kafka.go > reconcileKafkaPod function.
Does the reconciler delete each pod to apply all the config updates at every reconcile (delete pod, so the pod will restart with new static configuration) ?

Would this mean, even if there is no change in the configs, kafka pods are restarted always ?

Thanks in advance.
Kaushik

**Comment by baluchicken** [comment]
Hi @kaushiksrinivas if you have code related questions (how is this works, where is that), I recommend to join our [community slack](https://slack.banzaicloud.io)  and look for the #kafka-operator room. Some of your questions are already answered there. Moreover there is a huge community so maybe you will leverage from it as well.

Regarding Supertubes if you are interested on the features please contact us on our [web form.](https://banzaicloud.com/contact/)

**Comment by kaushiksrinivas** [comment]
Thanks @baluchicken

**Comment by kaushiksrinivas** [comment]
Hi @baluchicken 
I tried to post the queries in the banzai cloud community with #kafka-operator. But did not get responses.
is there any other channel which can be used ?

Can you please let us know if the rolling upgrade (for example config update to the kafka cluster) is only availble in the enterprise edition ?

Thanks,
Kaushik
