### ISSUE TITLE
kafka-operator rolling upgrade of broker pods.

### ISSUE THREAD

**Issue by britoaldan** [banzaicloud/kafka-operator#420]
If we use open source version of banzai kafka-operator, and we modify or update the read-only config "auto.create.topics.enable=false" will the kafka cluster get a rolling upgrade.

so in summary will the open source kafka-operator support rolling upgrades without supertubes core/pro enterprise versions.

And also in the documentation  we see that super-tubes as a pre-requisite for installing.
so is super-tubes a mandate incase of opensource operator ?

**Comment by stoader** [comment]
Updating readonly config will trigger rolling upgrade
