### ISSUE TITLE
rollback support for the banzai kafka operator

### ISSUE THREAD

**Issue by kaushiksrinivas** [banzaicloud/kafka-operator#421]
Comparing with helm, helm upgrade of a k8s release results in a revision creation and one can revert back to previous revisions via helm rollback commands with desired revision number.

When we switch to kafka operator, we understand that the kafkacluster CR spec can be modified and a rolling upgrade would occur. 
But what if we choose to rollback for various reasons to the previous configuration ? Does it mean one has to upgrade again with older values or is there any revision history maintained and rollback could be triggered ?

**Comment by kaushiksrinivas** [comment]
Hi @baluchicken @stoader 
Need your inputs.

**Comment by stoader** [comment]
currently no revision history maintained, you'll need to re-apply the original settings which will be applied again through the rolling upgrade mechanism.

Can you describe use cases that the current implementation is not a good fit for?

**Comment by kaushiksrinivas** [comment]
Thanks @stoader for the quick response.
While we use helm to deploy kafka, one can change any configuration revisions at helm and at any point of time there is a way to rollback to one of the older revisions seemlessly.

Suppose we upgrade to latest kafka image via operators with a bunch of configuration changes and stability issues are observed. 
There must be a way to simply rollback to previous stable state.
As of now, ways to do this is :
1. store all the revision changes locally and apply them again manually via operators.
2. write a helm chart to wrap the KafkaCluster CRD creation and use helm to store the revision history.

Would it be better if the operator itself maintains a revision and a single config update could bring us back to any older revisions ?

**Comment by stoader** [comment]
If you think in terms of creating resources in declarative way, various versions of the CR can be stored in the CD system of choice.

**Comment by kaushiksrinivas** [comment]
@stoader 
Are u suggesting to store the versions of the CR outside of the kubernetes system ? and use them to update the CR when required ?

**Comment by stoader** [comment]
yes
