### ISSUE TITLE
request for a property under "envoyconfig" in kafka CRD to pass loadBalancerIP to external loadBalancer like metallb

### ISSUE THREAD

**Issue by priyavj08** [banzaicloud/kafka-operator#423]
**Is your feature request related to a problem? Please describe.**
Currently in kafka CRD, under "envoyConfig" (externallistener) there is no property to set loadBalancerIP. I have a use case where I want to use metallb "spec.loadBalancerIP" functionality to allocate specific IP to envoy LB

**Describe the solution you'd like to see**
A clear and concise description of what would you like to happen.
Provide  property under "envoyconfig" in kafka CRD to set loadBalancerIP to be used by external loadBalancer like metallb

**Describe alternatives you've considered**

**Additional context**

**Comment by priyavj08** [comment]
hi, when will this be available?

thanks

**Comment by priyavj08** [comment]
@baluchicken is operator available with this fix?

thanks

**Comment by baluchicken** [comment]
@priyavj08  We just released it today.
