### ISSUE TITLE
Operator does not restart pod with status error

### ISSUE THREAD

**Issue by AceHack** [banzaicloud/kafka-operator#432]
**Describe the bug**
We use istio and istio injects istio-validation init container, there is also the jmx-exporter init container built into the operator.  If either one of these fail the pod status results in Error and the operator never restarts the pod leaving the cluster in a bad state until manual action is taken.

**Steps to reproduce the issue:**
Purposely cause an exception in an init container of the Kafka cluster, like add bad code to the jmx-exporter or if istio injection is enabled shut down the istiod service.

**Expected behavior**
Pods in error status should be restarted automatically by the operator.

**Comment by AceHack** [comment]
Awesome, thanks.

**Comment by AceHack** [comment]
Do you know what release this is in?

**Comment by hi-im-aren** [comment]
Hi, this should be in [v0.12.3](https://github.com/banzaicloud/kafka-operator/releases/tag/v0.12.3).
