### ISSUE TITLE
KAFKA_OPTS for broker config

### ISSUE THREAD

**Issue by zarkone** [banzaicloud/kafka-operator#437]
**Is your feature request related to a problem? Please describe.**

I want to setup `SASL_SSL` auth on my cluster. It requires `KAFKA_OPTS` to
be adjusted for each broker. I see that some other opts could be declared in configuration:

```go
	KafkaHeapOpts      string                        `json:"kafkaHeapOpts,omitempty"`
	KafkaJVMPerfOpts   string                        `json:"kafkaJvmPerfOpts,omitempty"`
```
However, I didn't find any way of how to pass `KAFKA_OPTS` to broker.

**Describe the solution you'd like to see**
Add `KafkaOpts` option for broker config, same as `KafkaHeapOpts`, `KafkaJVMPerfOpts`

**Describe alternatives you've considered**
I didn't find any way of how to pass `KAFKA_OPTS` to broker

**Comment by baluchicken** [comment]
Hi, you can use. the `envs` field for this purpose.
https://github.com/banzaicloud/kafka-operator/blob/daa4dd372e3510142b2e4afeae7c2f2cc0f3e7b5/pkg/sdk/v1beta1/kafkacluster_types.go#L62

**Comment by zarkone** [comment]
@baluchicken thank you!
