### ISSUE TITLE
Problem with PVC after resize disk

### ISSUE THREAD

**Issue by TritoXid** [banzaicloud/kafka-operator#469]
**Describe the bug**
I have kafka-cluster created by kafka-operator, but all disks are created by terraform (resource google_compute_disk) or via google console. PersistentVolume for this disks are created by yaml definition in helm. If I create new kafka-cluster everything working well. But after resize disk (e.g. 130GB to 140GB) kafka-operator started print this error:
```bash
"level":"error",
"ts":1601643182.6051328,
"logger":"controller",
"msg":"Reconciler error",
"reconcilerGroup":"kafka.banzaicloud.io",
"reconcilerKind":"KafkaCluster",
"controller":"KafkaCluster",
"name":"kafka",
"namespace":"kafka",
"error":"failed to reconcile resource: updating resource failed: persistentvolumeclaims 'kafka-0-storage-0-n6z54' is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize"
```
PersistentVolume for kafka broker was updated to new value 140GB but PersistentVolumeClaim not and kafka-operator started print previous error. PersistentVolumeClaim was created by kafka-operator not by me.
```bash
k get pvc <PVC_name> -o yaml
.
.
.
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 130Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: saz-kafka-data-1
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 140Gi
  phase: Bound
```
Manual PVC edit not working and k8s print me the same error like operator. In this moment when request storage and capacity storage have different value operator not working properly and if one broker pod is deleted operator not create new broker pod.

**Expected behavior**
My expectation is that after resize disk PVC will be update correctly and request and capacity storage will be same value.

**Additional context**
kubernetes version: 1.16.13-gke.1
kafka-operator version: 0.12.4

I really don't know what is bad, whether is bug in operator or I do something wrong.
Thanks for help me

**Comment by stoader** [comment]
That error message is returned by Kubernetes when kafka-operator tried to resize the PVC. In order this to work your Kubernetes volume provisioner must support volume expansion https://kubernetes.io/docs/concepts/storage/storage-classes/#allow-volume-expansion

**Comment by TritoXid** [comment]
Thank you. I updated storageClass definition with new options for kafka-cluster and kafka-operator started work correctly.
