### ISSUE TITLE
Update CC log4j configuration to use ConsoleAppender

### ISSUE THREAD

**Issue by amuraru** [banzaicloud/kafka-operator#496]
**Is your feature request related to a problem? Please describe.**

This came out as part of https://github.com/banzaicloud/kafka-operator/pull/495/files#r519745925
via @adamantal 
>Even though this is not what this PR is for, this log4j.properties seems odd to me.
Combining a file appender with /dev/stdout is suboptimal as log4j has a ConsoleAppender which is built for this particular purpose (supposedly containing more optimisation regarding pushing data to stdout).

**Describe the solution you'd like to see**

Update CC log4j properties file to use ConsoleAppender.

**Describe alternatives you've considered**
N/A

**Comment by adamantal** [comment]
Will fix it in #497.
