### ISSUE TITLE
create crd kafka.banzaicloud.io_kafkaclusters.yaml  fail

### ISSUE THREAD

**Issue by mathslimin** [banzaicloud/kafka-operator#513]
**Describe the bug**
$kubectl create -f config/base/crds/kafka.banzaicloud.io_kafkaclusters.yaml 
The CustomResourceDefinition "kafkaclusters.kafka.banzaicloud.io" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[cruiseControlConfig].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property

**Comment by mathslimin** [comment]
i think this compare is wrong                  
          {{- if semverCompare "< 1.18-0" .Capabilities.KubeVersion.GitVersion }}
                            - protocol
                            {{- end }}


kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by baluchicken** [comment]
Hi @mathslimin please use the latest released version of the operator. I just checked the referenced file https://github.com/banzaicloud/kafka-operator/blob/v0.13.1/config/base/crds/kafka.banzaicloud.io_kafkaclusters.yaml which should be fine. Also please use the combined crd files which is prepared for every release  https://github.com/banzaicloud/kafka-operator/releases/tag/v0.13.1 please find it under assets.
