### ISSUE TITLE
go.sum error

### ISSUE THREAD

**Issue by lengrongfu** [banzaicloud/kafka-operator#524]
**Describe the bug**
$ kafka-operator-0.14.0 % go mod vendor
```
verifying github.com/hashicorp/vault-plugin-auth-centrify@v0.5.4/go.mod: checksum mismatch
	downloaded: h1:GfRoy7NHsuR/ogmZtbExdJXUwbfwcxPrS9xzkyy2J/c=
	go.sum:     h1:tLY05v1tC+sfeeE6DF8RAC/MGw4gflomYfA28b4VULw=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```
go version go1.15.4 darwin/amd64

**Comment by schultheiszn** [comment]
Hi @lengrongfu,

unfortunately I wasn't able to reproduce your reported issue.
I've tested `go mod vendor` with golang `1.14.13` as well as with `1.15.6`. I'd suggest to clear the appropriate part of your `go env GOCACHE`

**Comment by lengrongfu** [comment]
Thanks , I found the problem, it is caused by Go GOPROXY and GOSUMDB ENV.
