### ISSUE TITLE
Manually modify the persistent storage function of the broker

### ISSUE THREAD

**Issue by lengrongfu** [banzaicloud/kafka-operator#541]
**Is your feature request related to a problem? Please describe.**

   Yes, the problem is that it is currently not possible to collect PVC usage for automatic expansion. Because the SCI protocol version used is low, I want to add a function to manually modify the CR file when the PVC storage is found to be insufficient and re-execute the expansion function.

**Describe the solution you'd like to see**
  By modifying the persistent. resource size in CR, the logic of expanding PVC is automatically executed.

**Describe alternatives you've considered**
By manually creating PVC and PV resources, Broker POD automatically associates the created PVC to achieve the purpose of increasing storage.

**Additional context**
  no

**Comment by stoader** [comment]
@lengrongfu changing the the size in the CR is applied to the PVC automatically.
