### ISSUE TITLE
Send kafka logs to centralised logging aggregator

### ISSUE THREAD

**Issue by dobrerazvan** [banzaicloud/kafka-operator#607]
**Is your feature request related to a problem? Please describe.**
We would like to send kafka logs to a central aggregator for indexing and searching. We have looked at the current features available in kafka operator and could find support for envoy and kafka sidecars.

**Describe the solution you'd like to see**
We plan un using fluentbit to forward logs to splunk and this requires fluetbit to run in a sidecar container and pick stdout/stderr information. Regarding the implementation we thought at two options:

- add a `sidecar` optional list attribute in kafkacluster crd that contains necessary options like sidecar body, global volumes, secrets
- create a separate crd for KafkaClusterSidecar with the same information as above and combine its resources with the KafkaCluster CR at pod creation time

What do you think of these 2 approaches or any for that matter?

Thanks

**Comment by tarokkk** [comment]
Is there any environment-specific detail why you can't use a simple approach like Logging Operator (tailing logs on the hosts)? https://github.com/banzaicloud/logging-operator

**Comment by dobrerazvan** [comment]
Thanks, I will investigate that option.

**Comment by ecojan** [comment]
Just to update on this ticket, the logging operator assumes the team deploying the Kafka operator + KafkaCluster have admin access to the Kubernetes Cluster (to create a daemonset and have access to tail logs from hosts), but this is not always the case in an environment managed by someone else.
