### ISSUE TITLE
Helm chart upgrade 0.4.6 -> 0.4.7/8 fails

### ISSUE THREAD

**Issue by sergii-koshel-exa** [banzaicloud/kafka-operator#612]
**Describe the bug**
Upgrading helm chart from version `0.4.6` to `0.4.7/8` fails with the error:

```
cannot patch "kafkaclusters.kafka.banzaicloud.io" with kind CustomResourceDefinition:  "" is invalid: patch: Invalid value:
"map[.... <patch value here>..." : cannot convert int64 to float64
```

**Steps to reproduce the issue:**
* Get helm chart `0.4.6` installed successfully.
* Try to upgrade to version `0.4.7` or `0.4.8`

**Expected behavior**
Helm chart upgraded successfully.

**Screenshots**

None

**Additional context**
k8s version: `GKE 1.19.9-gke.1400`
helm version: `v3.5.0`

**Comment by sergii-koshel-exa** [comment]
Full error with patch value: [out.log](https://github.com/banzaicloud/kafka-operator/files/6531674/out.log)

**Comment by stoader** [comment]
@sergii-koshel-exa have you upgraded the CRDs first before executing helm upgrade?

For me this worked just fine:
```
kubectl replace -f https://github.com/banzaicloud/kafka-operator/releases/download/v0.16.0/kafka-operator.crds.yaml

helm upgrade -n kafka kafka-operator banzaicloud-stable/kafka-operator --version 0.4.7 --reuse-values --skip-crds
```

```
kubectl replace -f https://github.com/banzaicloud/kafka-operator/releases/download/v0.16.1/kafka-operator.crds.yaml

helm upgrade -n kafka kafka-operator banzaicloud-stable/kafka-operator --version 0.4.8 --reuse-values --skip-crds
```

**Comment by sergii-koshel-exa** [comment]
After upgrading CRDs manually (`kubectl replace`) I can proceed with doing helm upgrade, thanks.
Closing it.
