### ISSUE TITLE
full CRD documentation

### ISSUE THREAD

**Issue by stephen-dahl** [banzaicloud/kafka-operator#66]
I may have missed it but I could not find documentation for all the KafkaCluster CRD fields other than the 1 example yaml

Please add documentation for all CRD fields.

For me, good docs would include:
* a full yaml file listing all possible fields to show the full structure.
* a field by field description listing possible values and their effects.

**Comment by baluchicken** [comment]
Thanks for the issue, we are going to provide a full crd documentation soon.
