### ISSUE TITLE
Docker image are hardcoded

### ISSUE THREAD

**Issue by prune998** [banzaicloud/kafka-operator#88]
**Is your feature request related to a problem? Please describe.**
When the Operator creates the Kafka cluster, it uses some external images which are hardcoded. You can see this in : 
https://github.com/banzaicloud/kafka-operator/blob/master/pkg/resources/kafka/pod.go#L78

**Describe the solution you'd like to see**
I would like a way to change these images URLs to use a private registry, for obvious security concerns and reliance issues.

**Describe alternatives you've considered**
No idea for now...

**Comment by baluchicken** [comment]
Thanks for the issue, we are going to allow to set those images via the CR.

**Comment by prune998** [comment]
Let me know if I can be of some help...
Thanks for this great piece of code I've been waiting for years (using strimzi in the meantime)

**Comment by baluchicken** [comment]
We just released a new version of operator 0.5.0 which contains the required changes, every image is configurable via the CR.
