### ISSUE TITLE
Support for prometheus operator and suggestions for grafana dashboard

### ISSUE THREAD

**Issue by rverma-nikiai** [banzaicloud/kafka-operator#91]
Can you provide instructions for how to push kafka metrics to existing prometheus. Maybe we can bundle this with some serviceMonitors.

**Comment by baluchicken** [comment]
Thanks for the issue, We will get back to you soon with the details.

**Comment by baluchicken** [comment]
@rverma-nikiai please check the following Readme.
https://github.com/banzaicloud/kafka-operator/blob/master/docs/monitoring.md

**Comment by baluchicken** [comment]
@rverma-nikiai Also please check Kafka Spotguide as well which automates the whole Kafka on Kubernetes experience, including deploying and configuring Monitoring infra for Kafka.
https://banzaicloud.com/blog/kafka-on-k8s-simplified/
