### ISSUE TITLE
Improve Helm chart

### ISSUE THREAD

**Issue by prune998** [banzaicloud/kafka-operator#97]
**Describe the solution you'd like to see**
The Helm chart is pretty basic. 
While I don't like Helm (better use Jsonnet), I would like to know if it will be the primary install choice for the comming releases ? 
If yes, I could give a shot and tweak few things, like templating the image/tag used and maybe other stuffs so it can be used to automate infrasctructure deployments.

**Describe alternatives you've considered**
Using Jsonnet, as Prometheus-operator do ?

**Comment by bonifaido** [comment]
Hi @prune998,

yes, Helm is our target deployment descriptor, hower on [some other projects we use Kustomize](https://github.com/banzaicloud/istio-operator/tree/release-1.2/config) as well. We are not planning to use Jsonnet however :)

Any kind of enhancements to the chart is welcome!

**Comment by bonifaido** [comment]
The Helm chart has improved a lot since then, so I'm closing this for now.
